apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 8001
      targetPort: 80
  type: LoadBalancer
