apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  username: ZGJ1c2Vy  # dbuser (base64 encoded)
  password: ZGJ1c2VycGFzczEyMw==  # dbuserpass123 (base64 encoded)
  database: ZG9jc2lnbl9kYg==  # docsign_db (base64 encoded)
