apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: nfs
    app: postgres
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /sorage01
    server: master01
